### ISSUE TITLE
itsmy.fyi

### ISSUE THREAD

**Issue by puppetbrown** [rishi-raj-jain/itsmy.fyi#173]

**Comment by rishi-raj-jain** [comment]
Bad luck! Try with a new slug? Here's a suggestion for you:

```markdown
slug: rishi-raj-jain-6j7
```

I promise I'll handle this better, but you'd have to create a [new issue](https://github.com/rishi-raj-jain/itsmy.fyi/issues/new?assignees=&labels=&template=itsyour.page-profile-data.yml&title=itsmy.fyi+-+%7BINSERT+NAME%7D+%28Optional%29) for now.

**Comment by rishi-raj-jain** [comment]
Bad luck! Here's what we found breaking in your data:

```markdown
Cannot read properties of null (reading 'indexOf')
```

Feel free to edit the issue again in case you've already got a link, else please re-try by creating a [new issue](https://github.com/rishi-raj-jain/itsmy.fyi/issues/new?assignees=&labels=&template=itsyour.page-profile-data.yml&title=itsmy.fyi+-+%7BINSERT+NAME%7D+%28Optional%29) for now.

**Comment by rishi-raj-jain** [comment]
Bad luck! Here's what we found breaking in your data:

```markdown
Cannot read properties of null (reading 'indexOf')
```

Feel free to edit the issue again in case you've already got a link, else please re-try by creating a [new issue](https://github.com/rishi-raj-jain/itsmy.fyi/issues/new?assignees=&labels=&template=itsyour.page-profile-data.yml&title=itsmy.fyi+-+%7BINSERT+NAME%7D+%28Optional%29) for now.
