### ISSUE TITLE
itsmy.fyi - Nikola Hristov

### ISSUE THREAD

**Issue by nikolaxhristov** [rishi-raj-jain/itsmy.fyi#69]
### itsmy.fyi Profile Data

```Markdown
---
slug: nikola
name: Nikola Hristov
about: Hey there, I'm Nikola on itsmy.fyi!
image: https://en.gravatar.com/userimage/46697537/59138035f27fbb36558d2a10dc3bcda6.png
links: [["Portfolio", "https://nikolahristov.tech"]]
socials: [["Twitter", "https://twitter.com/nikolaxhristov"]]
og:
  image: https://holopin.me/nikola
background:
  image: https://holopin.me/nikola
---
```

**Comment by rishi-raj-jain** [comment]
Thanks for using [itsmy.fyi](https://itsmy.fyi). Visit your [profile here ↗︎](https://itsmy.fyi/me/nikola).

Usage:
Remaining edits for next 1 minute: 2

**Comment by rishi-raj-jain** [comment]
Thanks for using [itsmy.fyi](https://itsmy.fyi). Visit your [profile here ↗︎](https://itsmy.fyi/me/nikola).

Usage:
Remaining edits for next 1 minute: 2

**Comment by rishi-raj-jain** [comment]
Thanks for using [itsmy.fyi](https://itsmy.fyi). Succesfully deleted your profile.

**Comment by nikolaxhristov** [comment]
---
slug: nikola
name: Nikola Hristov
about: CEO of @lightrix @playform
image: https://en.gravatar.com/userimage/46697537/59138035f27fbb36558d2a10dc3bcda6.png
links: [["Portfolio", "https://nikolahristov.tech/"]]
socials: [["Twitter", "https://twitter.com/nikolaxhristov"]]
og:
  image: https://holopin.me/nikola
background:
  image: https://holopin.me/nikola
---
