### ISSUE TITLE
itsmy.fyi - {INSERT NAME} (Optional)

### ISSUE THREAD

**Issue by chibuzorobilom** [rishi-raj-jain/itsmy.fyi#80]

**Comment by rishi-raj-jain** [comment]
Bad luck! Try with a new slug? Here's a suggestion for you: rishi-raj-jain-klf.

Usage:
Remaining edits for next 1 minute: 2

**Comment by rishi-raj-jain** [comment]
Too many updates in 1 minute. Please try again in a few minutes.
